// Code generated by "stringer -type=PlugID"; DO NOT EDIT.

package gogenie

import "fmt"

const _PlugID_name = "PlugAllPlugOnePlugTwo"

var _PlugID_index = [...]uint8{0, 7, 14, 21}

func (i PlugID) String() string {
	if i < 0 || i >= PlugID(len(_PlugID_index)-1) {
		return fmt.Sprintf("PlugID(%d)", i)
	}
	return _PlugID_name[_PlugID_index[i]:_PlugID_index[i+1]]
}
